name: PHP
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.0, 8.1 ]
        composer-prefer: [ lowest, dist ]
        psr-cache-version: [ ^1.0, ^2.0, ^3.0 ]
        exclude:
          # psr/cache v2 does not support PHP 7.*
          - psr-cache-version: ^2.0
            php-version: 7.3
          - psr-cache-version: ^2.0
            php-version: 7.4

          # psr/cache v3 does not support PHP 7.*
          - psr-cache-version: ^3.0
            php-version: 7.3
          - psr-cache-version: ^3.0
            php-version: 7.4
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-version }}-composer

      - run: |
          composer update \
          --prefer-${{ matrix.composer-prefer }} \
          --with='psr/cache:${{ matrix.psr-cache-version }}' \
          --ignore-platform-req=ext-newrelic \
          --no-progress

      - run: composer show

      - run: php -v

      - run: php -i

      - run: vendor/bin/phpunit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --no-progress --ignore-platform-req ext-newrelic

      - run: composer lint

      - run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          fail_ci_if_error: true

  bc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Nyholm/roave-bc-check-docker@0.1.0
