name: PHP
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.0, 8.1 ]
        composer-prefer: [ lowest, dist ]
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-version }}-composer

      - run: |
          composer update \
          --prefer-${{ matrix.composer-prefer }} \
          --ignore-platform-req=ext-newrelic \
          --no-progress

      - run: composer show
      - run: php -v
      - run: php -i
      - run: vendor/bin/phpunit

  bc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: roave/backward-compatibility-check

      - run: roave-backward-compatibility-check
